### ISSUE TITLE
[BUG] Can't install on Magento 2.4 (PHP 7.3 & PHP 7.4)

### ISSUE THREAD

**Issue by evilprophet** [tig-nl/persistentshoppingcart-magento2#6]
Currently, the module doesn't support Magento 2.4 and PHP 7.3. Do you plan to fix it?
It's not possible to install because in this and in the core module in compser.json PHP require is locked on `"~7.0|~7.1|~7.2"` and for magento/framework is locked on `"100.*|101.*|102.*"`. Magento 2.4 required PHP `7.3` and magento/framework `103.*`.

**To Reproduce**
1. Go to Magento 2 root folder
2. Run command 'composer require tig/persistent-shopping-cart-magento2'

**Expected result**
The module is installed on Magento 2.4

**Actual result**
```
Installation request for tig/persistent-shopping-cart-magento2 ^v1.0.4 -> satisfiable by tig/persistent-shopping-cart-magento2[1.0.4].
    - Conclusion: don't install magento/framework 102.0.6
    - tig/core 1.1.0 requires magento/framework 100.*|101.*|102.* -> satisfiable by magento/framework[102.0.6-p1, 102.0.6, 102.0.5-p2, 102.0.4-p2, 102.0.5, 102.0.3-p1, 102.0.4, 101.0.11, 102.0.2-p2, 101.0.10, 102.0.3, 101.0.9, 100.1.18, 102.0.2, 101.0.8, 102.0.1, 100.1.17, 102.0.0, 101.0.7, 100.1.16, 101.0.6, 100.1.15, 100.1.14, 101.0.5, 101.0.4, 100.1.13, 101.0.3, 100.1.12, 100.0.20, 101.0.2, 100.1.11, 100.1.10, 101.0.1, 100.0.19, 101.0.0, 100.0.18, 100.1.9, 101.0.0-rc30, 101.0.0-rc23, 101.0.0-rc22, 101.0.0-rc21, 100.2.0-rc20, 100.1.8, 100.0.17, 100.0.16, 100.1.7, 100.1.6, 100.0.15, 100.1.5, 100.0.14, 100.1.4, 100.0.13, 100.1.3, 100.1.2, 100.0.12, 100.1.1, 100.0.11, 100.0.10, 100.1.0, 100.1.0-rc3, 100.1.0-rc2, 100.1.0-rc1, 100.0.9, 100.0.8, 100.0.7, 100.0.6, 100.0.5, 100.0.4, 100.0.3, 100.0.2].
```

**Workaround**
None

**Please complete the following information**
- Magento version: 2.4.1
- PHP version: 7.3 or 7.4

**Comment by tig-jeffreybranderhorst** [comment]
Hi @evilprophet ,

Thank you for submitting this and thinking along to make the extension even better! We will test it on the new magento version and update the composer! 

Have a great day,
Jeffrey

**Comment by evilprophet** [comment]
Hi @tig-jeffreybranderhorst 
Can you estimate when your module will be available for Magento 2.4?

**Comment by tig-jeffreybranderhorst** [comment]
Hey @evilprophet ,

unfortunately I don't have an ETA yet for you. We have placed it on our backlog and will pick it up next sprint. After testing the extension in the sprint we will update the live version!

Have a great day,
Jeffrey

**Comment by drabikowy** [comment]
Dear @tig-jeffreybranderhorst.
Do you have any news on this matter? 
I would appreciate some information. 

Best regards, 
Tomasz

**Comment by mrlerch** [comment]
Any update on M2.4.x compatibility? I keep getting these errors when trying to install with composer:

  Problem 1
    - tig/persistent-shopping-cart-magento2 1.0.0 requires magento/framework 101.* -> found magento/framework[101.0.0-rc21, ..., 101.0.11] but the package is fixed to 103.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - tig/persistent-shopping-cart-magento2 1.0.1 requires magento/framework 100.*|101.* -> found magento/framework[100.0.2, ..., 100.2.0-rc20, 101.0.0-rc21, ..., 101.0.11] but the package is fixed to 103.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - tig/persistent-shopping-cart-magento2[1.0.2, ..., 1.0.4] require magento/framework 100.*|101.*|102.* -> found magento/framework[100.0.2, ..., 100.2.0-rc20, 101.0.0-rc21, ..., 101.0.11, 102.0.0, ..., 102.0.6-p1] but the package is fixed to 103.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires tig/persistent-shopping-cart-magento2 ^1.0 -> satisfiable by tig/persistent-shopping-cart-magento2[1.0.0, ..., 1.0.4].


Thanks,

Martin

**Comment by tig-jeffreybranderhorst** [comment]
Hi Martijn,

An exact release date I don't have yet. I know the compatible fix is made and is in test fase now. 

Have a great day,
Jeffrey

**Comment by mrlerch** [comment]
Perhaps you could release an alpha or beta version for dev stores to test as well? Just a thought.

Martin

**Comment by tig-jeffreybranderhorst** [comment]
Hi @mrlerch ,

We just released a new version that accepts 2.4.

Have a great day,
Jeffrey

**Comment by mrlerch** [comment]
Jeffrey, that’s great news. I will make sure to post back with any issues or comments.

Best wishes,

Martin

**Comment by mrlerch** [comment]
Hello Jeffrey, I just tried installing it via Composer, however it gives me an error:

composer require tig/persistent-shopping-cart-magento2
./composer.json has been updated
Running composer update tig/persistent-shopping-cart-magento2
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tig/core 1.1.0 requires magento/framework 100.*|101.*|102.* -> found magento/framework[100.0.2, ..., 100.2.0-rc20, 101.0.0-rc21, ..., 101.0.11, 102.0.0, ..., 102.0.6-p1] but the package is fixed to 103.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - tig/persistent-shopping-cart-magento2 1.0.5 requires tig/core 1.1.* -> satisfiable by tig/core[1.1.0].
    - Root composer.json requires tig/persistent-shopping-cart-magento2 ^1.0.5 -> satisfiable by tig/persistent-shopping-cart-magento2[1.0.5].

So I decided to use the git method instead. I did magento setup:upgrade, cleared all caches and statics and did a static content deploy for front and backend and another cache flush and reindex. Result:

When I go to Magento Admin -> Stores -> Configuration I get this:

1 exception(s):
Exception #0 (Exception): Notice: Undefined index: id in /var/www/html/domains/dev.proproductssales.com/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63

Exception #0 (Exception): Notice: Undefined index: id in /var/www/html/domains/dev.proproductssales.com/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63
<pre>#1 Magento\Config\Model\Config\Structure\Element\Iterator->setElements() called at [vendor/magento/module-config/Model/Config/Structure.php:146]
#2 Magento\Config\Model\Config\Structure->getTabs() called at [generated/code/Magento/Config/Model/Config/Structure/Interceptor.php:23]
#3 Magento\Config\Model\Config\Structure\Interceptor->getTabs() called at [vendor/magento/module-config/Model/Config/Structure.php:209]
#4 Magento\Config\Model\Config\Structure->getFirstSection() called at [generated/code/Magento/Config/Model/Config/Structure/Interceptor.php:59]
#5 Magento\Config\Model\Config\Structure\Interceptor->getFirstSection() called at [vendor/magento/module-config/Controller/Adminhtml/System/AbstractConfig.php:63]
#6 Magento\Config\Controller\Adminhtml\System\AbstractConfig->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#7 Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#8 Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#9 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#10 Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#11 Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->___callPlugins() called at [generated/code/Magento/Config/Controller/Adminhtml/System/Config/Index/Interceptor.php:32]
#12 Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186]
#13 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118]
#14 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#15 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#16 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#17 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#18 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#19 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#20 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#21 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
</pre>

I have disabled and removed the module from my source code tree and am awaiting additional instructions. Composer install preferred. Thank you!

Sincerely,

Martin

**Comment by pzlamaniec** [comment]
Hello, 
The `tig/core` package was not updated.
https://github.com/tig-nl/core-magento2/blob/master/composer.json
In the require section, there is still no PHP7.4 or Magento framework 103.x

**Comment by tig-jeffreybranderhorst** [comment]
Hi, 

We also edited the TIG core extension, you should be able to install it now. 

Have a great day,
Jeffrey

**Comment by mrlerch** [comment]
Hello Jeffrey, So I was able to install it using the composer method. After emptying cache and removing old static files I recreated static files, empties cache etc. Then went to Magento Admin -> Store -> Configuration -> Customer -> Persistent Shopping Cart and confirmed that the boxes are checked. I now placed an item into the shopping cart and if it works correctly this should be there in an hour or two from now. I will let you know. Thank you for fixing this!

**Comment by mrlerch** [comment]
Ok.. so I installed it, made sure it was enabled, added ann item to the cart, waited 2 hours, and checked again and the cart was empty. So, I don't think this works on Magento 2.4.2. Am I missing something?

**Comment by tig-jeffreybranderhorst** [comment]
Dear all, 

After consideration with our team. We decided that we will not actively maintain this module anymore. Please feel free to fork and improve the module as you see fit.

Have a great day,
Jeffrey

**Comment by mrlerch** [comment]
Hello Jeffrey,

Thanks for the update. That is a bit disappointing. Just to make sure. You are confirming that this is not working on M 2.4.2, correct? And you will no longer develop on this one, right?

Just checking.

**Comment by mrlerch** [comment]
For everyone else:
Here is what I found to make it work possibly without this extension...

https://magento.stackexchange.com/questions/86985/persistent-shopping-cart-and-guest-anonymous-users

The time duration for which Item saved into cart depends on two parameters

Magento Admin: System -> Configuration -> Web -> Session Cookie Management Cookie Lifetime
PHP.ini - session.gc_maxlifetime
Here your Session Cookie Management Cookie Lifetime should be less than the session.gc_maxlifetime.

The session.gc_maxlifetime will be honored first and then cookie lifetime.

So once the session is expired the cart will be emptied.


Hope that helps someone.

Martin

**Comment by tig-jeffreybranderhorst** [comment]
Hi @mrlerch,

Yes, that is correct. Good luck with the new way you found!

**Comment by mrlerch** [comment]
Thanks, but it’s not a “new” way. It’s “a way”. Probably not the best way, but better than the guest cart emptying itself out every 10 or 15 mins :)
